export const SET_CURRENT_USER = 'AUTH/SET_CURRENT_USER';
export const UNSET_CURRENT_USER = 'AUTH/UNSET_CURRENT_USER';

export const FETCH_USERS = 'AUTH/FETCH_USERS';

export const SET_USER_ISLOGGED = 'AUTH/SET_USER_ISLOGGED';
export const UNSET_USER_ISLOGGED = 'AUTH/UNSET_USER_ISLOGGED';

export const ADD_CONTACT = 'CONTACTS/ADD_CONTACT';
export const GET_CONTACTS = 'CONTACTS/GET_CONTACTS';
export const UPDATE_CONTACT = 'CONTACTS/UPDATE_CONTACT';
export const DELETE_CONTACT = 'CONTACTS/DELETE_CONTACT';

export const SET_ACTIVE_CONTACT = 'CONTACTS/SET_ACTIVE_CONTACT';
export const SET_ACTIVE_ADD_CONTACT_FORM =
  'CONTACTS/SET_ACTIVE_ADD_CONTACT_FORM';
export const UNSET_ACTIVE_ADD_CONTACT_FORM =
  'CONTACTS/UNSET_ACTIVE_ADD_CONTACT_FORM';

export const ENABLE_EDIT_MODE = 'CONTACTS/ENABLE_EDIT_MODE';
export const DISABLE_EDIT_MODE = 'CONTACTS/DISABLE_EDIT_MODE';
